### PR TITLE
Implement the sdl2 demo for the sys crate

### PR DESCRIPTION
**Pull request by Luni-4**
This PR fixes the first item of #1 

Haven't tried to load neither an overlay nor an icc profile, if you can provide those files, I'm willing to test them :)

Thanks for the review!

### CODE REVIEW

**Comment by ePirat** [comment]
You can find the example files in https://code.videolan.org/videolan/libplacebo/tree/master/demos (lena.jpg for the main image and vulkanlogo.png as overlay)

I've never tried the icc profile.

**Comment by lu-zero** [comment]
Great!

You might move the images in `assets/` btw.

**Comment by Luni-4** [comment]
> You can find the example files in https://code.videolan.org/videolan/libplacebo/tree/master/demos (lena.jpg for the main image and vulkanlogo.png as overlay)
> 
> I've never tried the icc profile.

I've already tested the demo with those example files, and it works on my part. I hope it could work on yours too.

**Comment by Luni-4** [comment]
> Great!
> 
> You might move the images in `assets/` btw.

Done, thanks!

**Pull request merged**
